Repository alibaba/AliOS-Things, pull requests merged in 2022-03, with the labels that each got.

#1371 cli: add exit command to exit a console
  components/cli/package.yaml
  components/cli/src/cli.c
  components/cli/src/cli_adapt.h
  components/cli/src/cli_console.c
  components/cli/src/cli_console.h
  components/cli/src/iobox/exit.c
Labels: in process

#1374 debug: correct taskbt/taskbtn usage message
  components/debug/src/debug_dumpsys.c
Labels: in process

#1387 Upgrade cJSON from version 1.7.8 to 1.7.15.
  components/cjson/include/cJSON.h
  components/cjson/src/cJSON.c
Labels: in process

#1389 Update cJSON to version 1.7.15
  application/example/example_legacy/id2_app/inc/cJSON.h
  application/example/example_legacy/id2_app/src/cJSON.c
  components/utility/cjson/cJSON.c
  components/utility/cjson/include/cJSON.h
Labels: in process

#1388 Update cJSON to version 1.7.15
  middleware/linkkit/sdk-c/examples/cJSON.c
  middleware/linkkit/sdk-c/examples/cJSON.h
  middleware/linkkit/sdk-c/src/tools/linkkit_tsl_convert/include/cJSON.h
  middleware/linkkit/sdk-c/src/tools/linkkit_tsl_convert/src/cJSON.c
  middleware/uagent/uota/src/utility/cjson/cJSON.c
  middleware/uagent/uota/src/utility/cjson/cJSON.h
  platform/mcu/esp8266/bsp/ESP8266_RTOS_SDK/include/json/cJSON.h
  platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.c
  platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.h
  utility/cjson/cJSON.c
  utility/cjson/include/cJSON.h
Labels: in process

#1400 Upgrade cJSON from version 1.6.0 to 1.7.15.
  app/example/id2_app/inc/cJSON.h
  app/example/id2_app/src/cJSON.c
  platform/mcu/esp8266/bsp/ESP8266_RTOS_SDK/include/json/cJSON.h
  platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.c
  platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.h
  platform/mcu/sv6266/drivers/sdk/components/third_party/cJSON/cJSON.c
  platform/mcu/sv6266/drivers/sdk/components/third_party/cJSON/cJSON.h
  utility/cjson/cJSON.c
  utility/cjson/cJSON_Utils.c
  utility/cjson/cJSON_Utils.h
  utility/cjson/include/cJSON.h
Labels: in process

#1396 Upgrade cJSON from version 1.6.0 to 1.7.15.
  framework/protocol/linkkit/sdk/iotx-sdk-c_clone/examples/linkkit/cJSON.c
  framework/protocol/linkkit/sdk/iotx-sdk-c_clone/examples/linkkit/cJSON.h
  framework/protocol/linkkit/sdk/iotx-sdk-c_clone/src/ref-impl/hal/os/ubuntu/cJSON.c
  framework/protocol/linkkit/sdk/iotx-sdk-c_clone/src/ref-impl/hal/os/ubuntu/cJSON.h
  framework/protocol/linkkit/sdk/iotx-sdk-c_clone/src/tools/linkkit_tsl_convert/include/cJSON.h
  framework/protocol/linkkit/sdk/iotx-sdk-c_clone/src/tools/linkkit_tsl_convert/src/cJSON.c
  framework/uOTA/src/utility/cjson/cJSON.c
  framework/uOTA/src/utility/cjson/cJSON.h
  platform/mcu/esp8266/bsp/ESP8266_RTOS_SDK/include/json/cJSON.h
  platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.c
  platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.h
  utility/cjson/cJSON.c
  utility/cjson/cJSON_Utils.c
  utility/cjson/cJSON_Utils.h
  utility/cjson/include/cJSON.h
Labels: in process

#1392 Upgrade cJSON from version 1.6.0 to 1.7.15.
  platform/mcu/esp8266/bsp/ESP8266_RTOS_SDK/include/json/cJSON.h
  platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.c
  platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.h
  utility/cjson/cJSON.c
  utility/cjson/cJSON_Utils.c
  utility/cjson/cJSON_Utils.h
  utility/cjson/include/cJSON.h
Labels: in process

#1398 Upgrade cJSON to version 1.7.15.
  components/utilities/cjson/cJSON.c
  components/utilities/cjson/cJSON.h
Labels: in process

#1401 Upgrade cJSON from version 1.6.0 to 1.7.15.
  application/example/example_legacy/id2_app/inc/cJSON.h
  application/example/example_legacy/id2_app/src/cJSON.c
  components/utility/cjson/cJSON.c
  components/utility/cjson/cJSON_Utils.c
  components/utility/cjson/cJSON_Utils.h
  components/utility/cjson/include/cJSON.h
  platform/mcu/esp8266/bsp/ESP8266_RTOS_SDK/include/json/cJSON.h
  platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.c
  platform/mcu/rtl8710bn/sdk/component/common/utilities/cJSON.h
  platform/mcu/sv6266/drivers/sdk/components/third_party/cJSON/cJSON.c
  platform/mcu/sv6266/drivers/sdk/components/third_party/cJSON/cJSON.h
Labels: in process

#1405 fix errors in haas_python_lib_bundles
  haas_lib_bundles/python/README.md
Labels: in process

#1404 fix errors in haas_python_lib_bundles
  haas_lib_bundles/python/README.md
Labels: in process

#1412 revised a readme.md in human_existence_detector
  .vscode/settings.json
  .vscode/tasks.json
  haas_lib_bundles/python/docs/examples/human_existence_detector/haas506/README.md
  haas_lib_bundles/python/docs/images/haas506案例图片/haas506_body_detect10.JPG
  haas_lib_bundles/python/docs/images/haas506案例图片/haas506_body_detect11.JPG
  haas_lib_bundles/python/docs/images/haas506案例图片/haas506_body_detect12.JPG
  haas_lib_bundles/python/docs/images/haas506案例图片/haas506_body_detect5.JPG
  haas_lib_bundles/python/docs/images/haas506案例图片/haas506_body_detect6.JPG
  haas_lib_bundles/python/docs/images/haas506案例图片/haas506_body_detect7.JPG
  haas_lib_bundles/python/docs/images/haas506案例图片/haas506_body_detect8.JPG
  haas_lib_bundles/python/docs/images/haas506案例图片/haas506_body_detect9.JPG
Labels: License Pass, Sensitive Information Pass

#1451 remove aisilopapp.c private info.
  example/bluetooth/aisilopapp/aisilopapp.c
Labels: in process, License Pass, Sensitive Information Pass

#1449 remove aisilopapp.c's private info.
  example/bluetooth/aisilopapp/aisilopapp.c
Labels: in process, License Pass, Sensitive Information Pass

#1450 remove aisilopapp.c private info.
  example/bluetooth/aisilopapp/aisilopapp.c
Labels: in process

#1448 remove aisilopapp.c's private info.
  example/bluetooth/aisilopapp/aisilopapp.c
Labels: in process

#1447 remove aisilopapp.c's private info.
  example/bluetooth/aisilopapp/aisilopapp.c
Labels: in process

#1446 remove linksdk_gateway_demo's private info.
  solutions/linksdk_gateway_demo/subdev_basic_demo.c
Labels: in process, License Pass, Sensitive Information Pass

#1459 haas1000:wifi: wifi_connect_task single instance
  hardware/chip/haas1000/hal/wifi_port.c
Labels: in process
