Repository alibaba/AliOS-Things, pull requests merged in 2022-05, with the labels that each got.

#1544 IssueID:1541:new VFS support and userspace support
  components/drivers/peripheral/flash/package.yaml
  components/drivers/peripheral/gpio/example/gpio_example.c
  components/drivers/peripheral/gpio/include/aos/gpio.h
  components/drivers/peripheral/gpio/include/aos/gpio_core.h
  components/drivers/peripheral/gpio/include/aos/gpioc.h
  components/drivers/peripheral/gpio/include/aos/gpioc_core.h
  components/drivers/peripheral/gpio/include/aos/hal/gpio.h
  components/drivers/peripheral/gpio/include/vfsdev/gpio_dev.h
  components/drivers/peripheral/gpio/package.yaml
  components/drivers/peripheral/gpio/src/gpio.c
  components/drivers/peripheral/gpio/src/gpioc.c
  components/drivers/peripheral/gpio/src/gpioc_csi.c
  components/py_engine/build_cmake.sh
Labels: in process, License Pass, Sensitive Information Pass

#1538 add motion API description document
  haas_lib_bundles/python/docs/haas_extended_api/motion.md
Labels: in process, License Pass, Sensitive Information Pass

#1532 add haaseduk1 document
  haas_lib_bundles/python/libraries/haaseduk1/README.md
  haas_lib_bundles/python/libraries/haaseduk1/code/board.json
  haas_lib_bundles/python/libraries/haaseduk1/code/haaseduk1.py
  haas_lib_bundles/python/libraries/haaseduk1/code/main.py
  haas_lib_bundles/python/libraries/haaseduk1/code/sh1106.py
Labels: License Pass, Sensitive Information Pass

#1537 add motion API
  haas_lib_bundles/python/libraries/motion/detections/fall_detection.py
  haas_lib_bundles/python/libraries/motion/detections/tap_detection.py
  haas_lib_bundles/python/libraries/motion/motion.py
Labels: in process, License Pass, Sensitive Information Pass

#1533 add TDS driver and documents
  haas_lib_bundles/python/docs/images/ext_TDS_外观图.png
  haas_lib_bundles/python/docs/images/ext_TDS_引脚图.png
  haas_lib_bundles/python/libraries/tds/README.md
  haas_lib_bundles/python/libraries/tds/tds.py
Labels: License Pass, Sensitive Information Pass

#1546 IssueID:1545:return value when function finish
  components/amp_adapter/platform/aos/peripheral/aos_hal_can.c
Labels: in process, License Conflict, Sensitive Information Pass

#1543 IssueID:1542:return value when function finish
  components/amp_adapter/platform/aos/peripheral/aos_hal_rtc.c
Labels: in process, License Pass, Sensitive Information Pass

#1540 IssueID:1500:add check for the inet_aton
  components/amp_adapter/platform/aos/network/aos_udp.c
Labels: License Pass, Sensitive Information Pass

#1550 add check after calling aos_new_mutex/sem, fixed #1549
  components/amp_adapter/platform/aos/peripheral/aos_hal_uart.c
Labels: in process, License Pass, Sensitive Information Pass

#1552 issue:1551: fix linksdk、ota、netmgr‘s whitescan error.
  components/linksdk/components/dynreg-mqtt/aiot_dynregmq_api.c
  components/netmgr/activation/activation.c
  components/netmgr/include/netmgr.h
  components/netmgr/netdev/src/netdev_cli.c
  components/netmgr/src/netmgr_service.c
  components/netmgr/src/netmgr_wifi.c
  components/ota/hal/ota_hal_digest.c
  components/ota/hal/ota_hal_trans.c
  components/ota/tools/upack_data_file.c
Labels: License Pass, Sensitive Information Pass

#1548 IssueID:1547:Improve driver development documents
  documentation/manual/.DS_Store
  documentation/manual/driver_development/adc_driver_development.md
  documentation/manual/driver_development/flash_driver_development.md
  documentation/manual/driver_development/i2c_driver_development.md
  documentation/manual/driver_development/pwm_driver_development.md
  documentation/manual/driver_development/spi_driver_development.md
  documentation/manual/driver_development/watchdog_driver_development.md
Labels: in process, License Pass, Sensitive Information Pass

#1556 Delete useless code, fixed #1555
  hardware/board/haaseduk1/startup/startup.c
Labels: in process, License Pass, Sensitive Information Pass

#1554 add return value check when calling sensor_i2c_close, fixed #1553
  hardware/board/haaseduk1/config/board.c
Labels: License Pass, Sensitive Information Pass

#1561 IssueID: 1560: lvgl stack decrease from 40KB to 4KB and modify lvgl s…
  components/py_engine/modules/display/display_lvgl.c
Labels: in process, License Pass, Sensitive Information Pass

#1564 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: in process, License Pass, Sensitive Information Pass

#1565 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: in process, License Pass, Sensitive Information Pass

#1571 IssueID:1570: vfs supports rootdir.
  components/vfs/vfs_inode.c
Labels: License Pass, Sensitive Information Pass

#1558 IssueID:1557:correct errors in ADS1115 driver and document
  haas_lib_bundles/python/libraries/ads1115/README.md
  haas_lib_bundles/python/libraries/ads1115/ads1x15.py
Labels: in process, License Pass, Sensitive Information Pass

#1559 add HaaS Python application remote upgrade SOP
  haas_lib_bundles/python/docs/startup/HaaS_Python_app_ota.md
Labels: in process, License Pass, Sensitive Information Pass

#1563 add motion detection API's example
  haas_lib_bundles/python/docs/examples/tap_detection/esp32/README.md
  haas_lib_bundles/python/docs/examples/tap_detection/esp32/code/main.py
  haas_lib_bundles/python/docs/examples/tap_detection/esp32/code/motion/detections/fall_detection.py
  haas_lib_bundles/python/docs/examples/tap_detection/esp32/code/motion/detections/tap_detection.py
  haas_lib_bundles/python/docs/examples/tap_detection/esp32/code/motion/motion.py
  haas_lib_bundles/python/docs/examples/tap_detection/esp32/code/mpu6886/mpu6886.py
Labels: in process, License Pass, Sensitive Information Pass

#1567 Change the logic of judgement on HaaS EDU K1's hardware version
  haas_lib_bundles/python/libraries/haaseduk1/code/haaseduk1.py
Labels: in process, License Pass, Sensitive Information Pass

#1572 trace: fix whitescan bugs
  components/trace/Config/SEGGER_SYSVIEW_AliOSThings.c
Labels: License Pass, Sensitive Information Pass

#1573 init: fix build error when trace is enabled
  components/init/aos_init.c
Labels: in process, License Conflict, Sensitive Information Pass

#1586 IssueID:1579:HaaSEDUK1 flash driver for new driver framework
  hardware/board/haaseduk1/board_test/board_test.c
  hardware/board/haaseduk1/config/partition_conf.c
  hardware/board/haaseduk1/package.yaml
Labels: in process, License Pass, Sensitive Information Pass

#1588 IssueID:1582:OTA supports new flash API
  components/ota/hal/.ota_hal_fs_plat.c.swp
  components/ota/hal/ota_hal_aos_param.c
  components/ota/hal/ota_hal_aos_plat.c
  components/ota/hal/ota_hal_vfs_param.c
  components/ota/package.yaml
  hardware/chip/haas1000/aos/ota_port.c
  hardware/chip/haas1000/aos/ota_port.h
  hardware/chip/rtl872xd/aos/ota_port.c
  hardware/chip/rtl872xd/aos/ota_port.h
Labels: in process, License Pass, Sensitive Information Pass

#1589 IssueID:1581:access fails after the same I2C device is opened for more than one time
  components/py_engine/modules/driver/i2c.c
Labels: in process, License Conflict, Sensitive Information Pass

#1587 IssueID:1580:HaaS200 flash driver for new driver framework
  hardware/board/haas200/config/partition_conf.c
  hardware/chip/rtl872xd/aos_adapter/flash.c
  hardware/chip/rtl872xd/aos_adapter/pwm.c
  hardware/chip/rtl872xd/aos_adapter/uart.c
  hardware/chip/rtl872xd/csi_driver/uart/uart.c
  hardware/chip/rtl872xd/package.yaml
Labels: in process, License Pass, Sensitive Information Pass

#1585 IssueID:1578:HaaS100 flash driver for new driver framework
  hardware/board/haas100/config/k_config.c
  hardware/board/haas100/config/partition_conf.c
  hardware/board/haas100/package.yaml
  hardware/board/haas100/startup/startup.c
  hardware/chip/haas1000/aos_adapter/flash.c
  hardware/chip/haas1000/aos_adapter/pwm.c
  hardware/chip/haas1000/aos_adapter/uart.c
  hardware/chip/haas1000/package.yaml
Labels: in process, License Pass, Sensitive Information Pass

#1577 IssueID:1576:Improve libc_stub
  components/libc_stub/compilers/gcc/sys/ioctl.h
  components/libc_stub/compilers/gcc/sys/termios.h
  components/libc_stub/newlib_stub.c
  components/libc_stub/package.yaml
Labels: in process, License Pass, Sensitive Information Pass

#1575 IssueID:1574:Improve UART driver framework.
  components/drivers/peripheral/uart/example/uart_example.c
  components/drivers/peripheral/uart/include/aos/hal/uart.h
  components/drivers/peripheral/uart/include/aos/tty.h
  components/drivers/peripheral/uart/include/aos/tty_core.h
  components/drivers/peripheral/uart/include/vfsdev/uart_dev.h
  components/drivers/peripheral/uart/package.yaml
  components/drivers/peripheral/uart/src/tty.c
  components/drivers/peripheral/uart/src/uart_dev.c
Labels: License Pass, Sensitive Information Pass

#1595 update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: in process, License Pass, Sensitive Information Pass

#1598 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: in process, License Pass, Sensitive Information Pass

#1600 change the function return as void, fixed #1599
  components/amp_adapter/platform/aos/aos_system.c
Labels: in process, License Pass, Sensitive Information Pass

#1590 fix linksdk whitescan error
  components/linksdk/core/aiot_mqtt_api.c
Labels: in process, License Pass, Sensitive Information Pass

#1605 Change the type of address into unsigned int to print, fixes #1604
  hardware/chip/haas1000/hal/audio.c
Labels: in process, License Pass, Sensitive Information Pass

#1602 add return value for every condition, fixed #1601
  hardware/chip/haas1000/hal/audio.c
Labels: in process, License Pass, Sensitive Information Pass

#1613 fix uart.on() failed # 1584
  components/amp_adapter/platform/esp_idf/peripheral/aos_hal_uart.c
Labels: in process, License Pass, Sensitive Information Pass

#1615 change uart doc, fix #1614
  haas_lib_bundles/python/docs/haas_extended_api/driver/uart.md
Labels: in process, License Pass, Sensitive Information Pass

#1603 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: in process, License Pass, Sensitive Information Pass

#1617 Fix the incorrect pointer usage, fixed #1616
  components/udisplay/src/udisplay.c
Labels: in process, License Pass, Sensitive Information Pass

#1620 IssueID:1619: clean netmgr_wifi.c private info.
  components/netmgr/src/netmgr_wifi.c
Labels: in process, License Pass, Sensitive Information Pass

#1607 Fix board disattach spelling error for modbus
  components/netmgr/src/netmgr_wifi.c
Labels: License Pass, Sensitive Information Pass

#1632 fix build err
  components/amp_adapter/package.yaml
  components/amp_adapter/platform/aos/app_ota.c
  components/amp_adapter/platform/esp_idf/peripheral/aos_hal_system.c
  components/amp_adapter/platform/esp_idf/peripheral/app_ota.c
Labels: in process, License Pass, Sensitive Information Pass

#1628 add esp32 demo: obstacle avoidance, fixes #1627
  haas_lib_bundles/python/docs/examples/obstacle_avoidance/esp32/README.md
  haas_lib_bundles/python/docs/examples/obstacle_avoidance/esp32/code/board.json
  haas_lib_bundles/python/docs/examples/obstacle_avoidance/esp32/code/buzzer.py
  haas_lib_bundles/python/docs/examples/obstacle_avoidance/esp32/code/hcsr04.py
  haas_lib_bundles/python/docs/examples/obstacle_avoidance/esp32/code/main.py
  haas_lib_bundles/python/docs/examples/obstacle_avoidance/esp32/link_platform/model.zip
  haas_lib_bundles/python/docs/images/雷达避障系统/ESP32_连线.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/ext_蜂鸣器_外观图.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/ext_超声波测距_定义尺寸.png
  haas_lib_bundles/python/docs/images/雷达避障系统/main.py.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/创建云端设备1.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/创建云端设备2.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/创建云端设备3.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/创建云端设备4.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/创建工程.png
  haas_lib_bundles/python/docs/images/雷达避障系统/功能定义.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/原理图.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/推送步骤.png
  haas_lib_bundles/python/docs/images/雷达避障系统/推送步骤log.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/步骤概述.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/距离识别结果记录.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/选择本地更新.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_HaaS控制台查看设备.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_HaaS控制台绑定产品.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_IS关联产品.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_IS创建移动应用.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_IS新建项目.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_IS项目管理.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_产品列表页.jpg
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_发布产品.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_发布物模型.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_完成创建产品.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_导入完成.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_尚未添加任何功能.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_快速导入.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_批量添加.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_新建产品.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_添加设备.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_物模型数据.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_物联网平台.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_空产品页.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_设备列表.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_设备证书.png
  haas_lib_bundles/python/docs/images/雷达避障系统/雷达避障系统_物联网平台开发_设备详情.png
Labels: in process, License Pass, Sensitive Information Pass

#1635 IssueID:#1633: add temp_humidity_speaker example
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/README.md
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/board.json
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/cht8305.py
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/main.py
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/SYS_TONE_0.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/SYS_TONE_1.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/SYS_TONE_2.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/SYS_TONE_3.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/SYS_TONE_4.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/SYS_TONE_5.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/SYS_TONE_6.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/SYS_TONE_7.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/SYS_TONE_8.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/SYS_TONE_9.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/SYS_TONE_MEASURE_WORD_shi.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/SYS_TONE_dian.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/centigrade.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/connected.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/humidity.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/negative.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/poweron.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/resource/temperature.wav
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/sh1106.py
  haas_lib_bundles/python/docs/examples/temp_humidity_speaker/haaseduk1/code/speech_utils.py
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/3部导学.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/device_tripe.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/新建温湿度检测产品.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/温湿度检测三元组信息.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/温湿度检测产品列表.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/温湿度检测产品功能定义.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/温湿度检测产品管理设备.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/温湿度检测发布上线.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/温湿度检测屏幕显示.jpg
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/温湿度检测添加设备.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/温湿度检测物模型数据.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/温湿度检测编辑草稿.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/温湿度检测设备信息.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/温湿度检测设备状态及属性.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/设备端-project-create.png
  haas_lib_bundles/python/docs/images/temp_humidity_speaker/设备端-project.png
Labels: License Pass, Sensitive Information Pass

#1641 add m5stackcore2 demo-smart_traffic_light,fixes #1640
  haas_lib_bundles/python/docs/examples/smart_traffic_light/esp32/README.md
  haas_lib_bundles/python/docs/examples/smart_traffic_light/esp32/code/board.json
  haas_lib_bundles/python/docs/examples/smart_traffic_light/esp32/code/cloudAI.py
  haas_lib_bundles/python/docs/examples/smart_traffic_light/esp32/code/main.py
  haas_lib_bundles/python/docs/examples/smart_traffic_light/esp32/code/rgb.py
  haas_lib_bundles/python/docs/examples/vehicle_congestion_detect/esp32/README.md
  haas_lib_bundles/python/docs/images/smart_traffic_light/AI_HaaS官网.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/AI_HaaS控制台.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_HaaSStudio_创建工程.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_HaaS官网_绑定物联网产品.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_HaaS控制台_查看三元组.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_IOTStudio_手机预览.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_IOTStudio应用保存预览.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_案例步骤.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_IS关联产品.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_IS创建移动应用.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_IS新建项目.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_IS设置设备属性.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_IS设置设备属性1.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_IS设置设备属性2.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_IS项目管理.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_发布物模型.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_应用页面配置1.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_应用页面配置2.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_应用页面配置3.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_应用页面配置4.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_快速导入.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_批量添加.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_物联网平台开发_新建产品.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_设备识别结果.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_连接图1.png
  haas_lib_bundles/python/docs/images/smart_traffic_light/智能红绿灯_连接图2.png
Labels: in process, License Pass, Sensitive Information Pass

#1636 Change the expression, fixes #1634
  hardware/chip/haas1000/aos/ota_port.c
Labels: in process, License Pass, Sensitive Information Pass

#1638 enable freetype for lvgl & remove little_ui dir
  components/freetype/package.yaml
  components/py_engine/modules/display/esp32/lv_conf.h
  components/py_engine/modules/display/haas/lv_conf.h
  components/py_engine/modules/portmod.cmake
  components/py_engine/package.yaml
  haas_lib_bundles/python/docs/haas_extended_api/ui_lite/UI_Lite_startup.md
  haas_lib_bundles/python/docs/haas_extended_api/ui_lite/UI_Lite_widgets.md
Labels: in process, License Pass, Sensitive Information Pass

#1646 Rename FEATURE_REQUEST.yml to FeatureRequest_en.yml
  .github/ISSUE_TEMPLATE/FeatureRequest_en.yml
Labels: in process, License Pass, Sensitive Information Pass

#1655 IssueID:1651: modify uln2003 input from pullup to pushpull.
  haas_lib_bundles/python/libraries/uln2003/README.md
Labels: in process, License Pass, Sensitive Information Pass

#1656 Create FeatureRequest_zh.yml
  .github/ISSUE_TEMPLATE/FeatureRequest_zh.yml
Labels: in process, License Pass, Sensitive Information Pass

#1674 Skylar cai patch 2
  .github/ISSUE_TEMPLATE/BugReport_zh.yml
  .github/ISSUE_TEMPLATE/FeatureRequest_zh.yml
Labels: in process, License Pass, Sensitive Information Pass

#1661 create driver and api for the fheartbeat sensor #1660
  haas_lib_bundles/python/docs/images/fheartbeat.png
  haas_lib_bundles/python/docs/images/fheatbeat-princ.png
  haas_lib_bundles/python/libraries/fheartbeat/README.md
  haas_lib_bundles/python/libraries/fheartbeat/fheartbeat.py
Labels: in process, License Pass, Sensitive Information Pass

#1663 add traker rockerkey ws2812 motorspeed driver and api for new sensors #1662
  haas_lib_bundles/python/docs/images/motorspeed.png
  haas_lib_bundles/python/docs/images/rockerkey.png
  haas_lib_bundles/python/docs/images/tracker.png
  haas_lib_bundles/python/docs/images/ws2812.png
  haas_lib_bundles/python/docs/images/ws2812_24bits.png
  haas_lib_bundles/python/docs/images/ws2812_seq.png
  haas_lib_bundles/python/libraries/motorspeed/README.md
  haas_lib_bundles/python/libraries/motorspeed/motorspeed.py
  haas_lib_bundles/python/libraries/rockerkey/README.md
  haas_lib_bundles/python/libraries/rockerkey/ads1x15.py
  haas_lib_bundles/python/libraries/rockerkey/rockerkey.py
  haas_lib_bundles/python/libraries/tracker/README.md
  haas_lib_bundles/python/libraries/tracker/tracker.py
  haas_lib_bundles/python/libraries/ws2812/README.md
  haas_lib_bundles/python/libraries/ws2812/ws2812.py
Labels: in process, License Pass, Sensitive Information Pass

#1664 update for online upgrade
  components/py_engine/adapter/esp32/fs/boot.py
  components/py_engine/adapter/esp32/m5stackcore2/boot.py
  components/py_engine/adapter/haas/fs/boot.py
  components/py_engine/external/libs/espc3/libotaput.a
  components/py_engine/package.yaml
  hardware/board/esp_c3_32s_kit/package.yaml
  hardware/board/esp_s3_12k_kit/package.yaml
  hardware/board/m5stackcore2/package.yaml
  hardware/board/nodemcu32s/package.yaml
  solutions/py_engine_esp32_demo/package.yaml
Labels: in process, License Pass, Sensitive Information Pass

#1653 pwm: convert pwm duty type to float, fix #1652
  components/amp_adapter/platform/aos/peripheral/aos_hal_pwm.c
Labels: License Pass, Sensitive Information Pass

#1650 add alcohol_detector, fix #1649
  haas_lib_bundles/python/docs/examples/alcohol_detector/haaseduk1/README.md
  haas_lib_bundles/python/docs/examples/alcohol_detector/haaseduk1/code/board.json
  haas_lib_bundles/python/docs/examples/alcohol_detector/haaseduk1/code/buzzer.py
  haas_lib_bundles/python/docs/examples/alcohol_detector/haaseduk1/code/main.py
  haas_lib_bundles/python/docs/examples/alcohol_detector/haaseduk1/code/mq3.py
  haas_lib_bundles/python/docs/examples/alcohol_detector/haaseduk1/code/sh1106.py
  haas_lib_bundles/python/docs/images/alcohol_detector/三步导学.png
  haas_lib_bundles/python/docs/images/alcohol_detector/云平台-创建产品.png
  haas_lib_bundles/python/docs/images/alcohol_detector/云平台-创建设备.png
  haas_lib_bundles/python/docs/images/alcohol_detector/云平台-功能定义.png
  haas_lib_bundles/python/docs/images/alcohol_detector/云平台-发布上线.png
  haas_lib_bundles/python/docs/images/alcohol_detector/云平台-测试结果显示.png
  haas_lib_bundles/python/docs/images/alcohol_detector/云平台-结果显示.png
  haas_lib_bundles/python/docs/images/alcohol_detector/云平台-编辑自定义功能.png
  haas_lib_bundles/python/docs/images/alcohol_detector/云平台-编辑草稿.png
  haas_lib_bundles/python/docs/images/alcohol_detector/云平台-设备三元组信息.png
  haas_lib_bundles/python/docs/images/alcohol_detector/云平台-设备上线.png
  haas_lib_bundles/python/docs/images/alcohol_detector/云平台-设备物模型信息.png
  haas_lib_bundles/python/docs/images/alcohol_detector/云平台-设备物模型数据.png
  haas_lib_bundles/python/docs/images/alcohol_detector/前往定义物模型.png
  haas_lib_bundles/python/docs/images/alcohol_detector/硬件接线图.png
  haas_lib_bundles/python/docs/images/alcohol_detector/设备端-代码区.png
  haas_lib_bundles/python/docs/images/alcohol_detector/设备端-创建工程向导.png
  haas_lib_bundles/python/docs/images/alcohol_detector/设备端-创建工程确认.png
  haas_lib_bundles/python/docs/images/alcohol_detector/设备端-测试结果显示.jpg
  haas_lib_bundles/python/docs/images/ext_mq3_实物.png
Labels: License Pass, Sensitive Information Pass

#1666 IssueID:1654:correct HaaSPython Uart return value.
  components/py_engine/modules/driver/uart.c
Labels: in process, License Pass, Sensitive Information Pass

#1676 Update README.md
  README.md
Labels: in process, License Pass, Sensitive Information Pass

#1686 Update README.md
  hardware/chip/espressif_esp32_c3/README.md
Labels: in process

#1687 Update README.md
  hardware/board/esp_c3_32s_kit/README.md
Labels: in process

#1681 IssuID:1626:Comparing an array to null is not useful "dp->vfs_dirent.d_name != NULL" since the test will always evaluate as true
  components/ramfs/src/ramfs_vfs.c
Labels: License Pass, Sensitive Information Pass

#1680 IssueID:1625:The called function is unsafe for security related code
  components/ramfs/src/ramfs.c
Labels: License Pass, Sensitive Information Pass

#1667 support network interface for haaseduk1 #1642
  components/amp_adapter/include/aos_log.h
  components/amp_adapter/include/aos_network.h
  components/amp_adapter/include/aos_system.h
  components/amp_adapter/package.yaml
  components/amp_adapter/platform/aos/aos_log.c
  components/amp_adapter/platform/aos/aos_system.c
  components/amp_adapter/platform/aos/network/aos_network.c
  components/amp_adapter/platform/aos/network/aos_wifi.c
  components/py_engine/adapter/haas/CMakeLists.txt
  components/py_engine/adapter/haas/modnetwork.c
  components/py_engine/modules/netmgr/modnetmgr.c
  haas_lib_bundles/python/docs/haas_extended_api/network.md
Labels: License Pass, Sensitive Information Pass

#1668 support sntp interface. #1657
  components/py_engine/modules/sntp/aos/modsntp.c
  components/py_engine/modules/sntp/esp32/modsntp.c
  haas_lib_bundles/python/docs/haas_extended_api/sntp.md
Labels: in process, License Pass, Sensitive Information Pass

#1696 IssueID:1683:Python example ultrasonic ranging
  haas_lib_bundles/python/docs/examples/ultrasonic_ranging/m5stackcore2/README.md
  haas_lib_bundles/python/docs/examples/ultrasonic_ranging/m5stackcore2/code/board.json
  haas_lib_bundles/python/docs/examples/ultrasonic_ranging/m5stackcore2/code/main.py
  haas_lib_bundles/python/docs/examples/ultrasonic_ranging/m5stackcore2/code/urm37.py
  haas_lib_bundles/python/docs/images/ultrasonic_ranging/create.png
  haas_lib_bundles/python/docs/images/ultrasonic_ranging/create_1.png
  haas_lib_bundles/python/docs/images/ultrasonic_ranging/device.png
  haas_lib_bundles/python/docs/images/ultrasonic_ranging/device_1.png
  haas_lib_bundles/python/docs/images/ultrasonic_ranging/display.png
  haas_lib_bundles/python/docs/images/ultrasonic_ranging/hardware_connection.png
  haas_lib_bundles/python/docs/images/ultrasonic_ranging/product.png
  haas_lib_bundles/python/docs/images/ultrasonic_ranging/product_1.png
  haas_lib_bundles/python/docs/images/ultrasonic_ranging/product_2.png
  haas_lib_bundles/python/docs/images/ultrasonic_ranging/result.png
  haas_lib_bundles/python/docs/images/ultrasonic_ranging/triple.png
Labels: License Pass, Sensitive Information Pass

#1697 IssueID:1684:Python example power meter
  haas_lib_bundles/python/docs/examples/power_meter/nodemcu32s/README.md
  haas_lib_bundles/python/docs/examples/power_meter/nodemcu32s/code/board.json
  haas_lib_bundles/python/docs/examples/power_meter/nodemcu32s/code/dds5188.py
  haas_lib_bundles/python/docs/examples/power_meter/nodemcu32s/code/main.py
  haas_lib_bundles/python/docs/images/power_meter/create.png
  haas_lib_bundles/python/docs/images/power_meter/create_1.png
  haas_lib_bundles/python/docs/images/power_meter/device.png
  haas_lib_bundles/python/docs/images/power_meter/device_1.png
  haas_lib_bundles/python/docs/images/power_meter/hardware_connection.png
  haas_lib_bundles/python/docs/images/power_meter/product.png
  haas_lib_bundles/python/docs/images/power_meter/product_1.png
  haas_lib_bundles/python/docs/images/power_meter/product_2.png
  haas_lib_bundles/python/docs/images/power_meter/product_3.png
  haas_lib_bundles/python/docs/images/power_meter/product_4.png
  haas_lib_bundles/python/docs/images/power_meter/product_5.png
  haas_lib_bundles/python/docs/images/power_meter/result.png
  haas_lib_bundles/python/docs/images/power_meter/triple.png
Labels: in process, License Pass, Sensitive Information Pass

#1698 IssueID:1685:Python example playing with cats
  haas_lib_bundles/python/docs/examples/playing_with_cats/nodemcu32s/README.md
  haas_lib_bundles/python/docs/examples/playing_with_cats/nodemcu32s/code/board.json
  haas_lib_bundles/python/docs/examples/playing_with_cats/nodemcu32s/code/main.py
  haas_lib_bundles/python/docs/examples/playing_with_cats/nodemcu32s/code/uln2003.py
  haas_lib_bundles/python/docs/images/playing_with_cats/cat.gif
  haas_lib_bundles/python/docs/images/playing_with_cats/hardware_connection.png
Labels: License Pass, Sensitive Information Pass

#1702 Add README.md file
  hardware/board/esp_c3_32s_kit/README.md
  hardware/board/esp_s3_12k_kit/README.md
  hardware/chip/espressif_esp32_c3/README.md
  hardware/chip/espressif_esp32_s3/README.md
Labels: in process, License Pass, Sensitive Information Pass

#1703 Add README.md file
  hardware/board/m5stackcore2/README.md
  hardware/board/nodemcu32s/README.md
  hardware/board/pywifiesp32/README.md
  hardware/chip/espressif_esp32/README.md
Labels: License Pass, Sensitive Information Pass

#1714 haaseduk1: add README.md, fix #1705
  hardware/board/haaseduk1/README.md
Labels: License Pass, Sensitive Information Pass

#1713 haas100: add README.md, fix #1705
  hardware/board/haas100/README.md
Labels: in process, License Pass, Sensitive Information Pass

#1712 haas200: add README.md, fix #1705
  hardware/board/haas200/README.md
Labels: in process, License Pass, Sensitive Information Pass

#1710 rtl872xd: add README.md, fix #1705
  hardware/chip/rtl872xd/README.md
Labels: License Pass, Sensitive Information Pass

#1709 haas1000: add README.md, fix #1705
  hardware/chip/haas1000/README.md
Labels: in process, License Pass, Sensitive Information Pass

#1708 armv8m: add README.md, fix #1705
  hardware/arch/armv8m/README.md
Labels: in process, License Pass, Sensitive Information Pass

#1707 riscv: add README.md, fix #1705
  hardware/arch/riscv/README.md
Labels: License Pass, Sensitive Information Pass

#1682 fix linksdk_demo cannot use file system error
  solutions/linksdk_demo/package.yaml
Labels: in process, License Pass, Sensitive Information Pass

#1715 IssueID:1704:Add the source code of auto feeder.
  haas_lib_bundles/python/docs/examples/auto_feeder/haaseduk1/README.md
  haas_lib_bundles/python/docs/examples/auto_feeder/haaseduk1/code/board.json
  haas_lib_bundles/python/docs/examples/auto_feeder/haaseduk1/code/hx711.py
  haas_lib_bundles/python/docs/examples/auto_feeder/haaseduk1/code/main.py
  haas_lib_bundles/python/docs/examples/auto_feeder/haaseduk1/code/uln2003.py
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_IS关联产品.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_IS关联设备.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_IS创建移动应用.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_IS新建项目.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_IS项目管理.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_创建工程.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_发布产品.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_发布物模型.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_完成创建产品.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_导入完成.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_尚未添加任何功能.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_应用余粮统计.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_应用开关时间.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_应用开始投喂.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_应用投喂次数.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_应用投喂次数清零.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_应用标题.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_应用预览.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_快速导入.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_接线示意图.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_新建产品.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_添加设备.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_物模型数据.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_物联网平台.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_移动应用编辑.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_空产品页.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_设备列表.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_设备证书.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_设备详情.png
  haas_lib_bundles/python/docs/images/auto_feeder/宠物粮投喂器_连线图.png
Labels: in process, License Pass, Sensitive Information Pass

#1730 IssueID:1728:esp32(m5stackcore2) supports sd card.
  components/py_engine/adapter/esp32/main.c
  components/py_engine/adapter/esp32/main/CMakeLists.txt
  components/py_engine/adapter/esp32/moduos.c
  components/py_engine/adapter/esp32/mpconfigport.h
  hardware/chip/espressif_esp32/package.yaml
Labels: in process, License Pass, Sensitive Information Pass

#1731 disable s3 online upgrade
  hardware/board/esp_s3_12k_kit/package.yaml
Labels: in process, License Pass, Sensitive Information Pass

#1738 debug: debug command print cpu information, fix #1735
  components/debug/src/debug_overview.c
Labels: in process, License Pass, Sensitive Information Pass

#1739 debug: fix build issue in debug lastword, fix #1735
  components/debug/package.yaml
  components/debug/src/debug_lastword.h
Labels: in process, License Pass, Sensitive Information Pass

#1737 Change the return value type, fixed #1736
  hardware/chip/haas1000/aos/ota_port.c
Labels: in process, License Pass, Sensitive Information Pass

#1754 BugID:1732:Add the source code of electronic scale sensor.
  haas_lib_bundles/python/docs/images/ele_scale/电子秤_安装图.png
  haas_lib_bundles/python/docs/images/ele_scale/电子秤_惠斯通电桥.png
  haas_lib_bundles/python/docs/images/ele_scale/电子秤_接线示意图.png
  haas_lib_bundles/python/docs/images/ele_scale/电子秤_测量原理图.png
  haas_lib_bundles/python/libraries/ele_scale/README.md
  haas_lib_bundles/python/libraries/ele_scale/ele_scale.py
Labels: in process, License Pass, Sensitive Information Pass

#1742 curl: fix build issue on haas200, fix #1741
  components/curl/package.yaml
  components/mbedtls/platform/include/platform_config.h
Labels: in process, License Pass, Sensitive Information Pass

#1759 posix: add pthread_mutex_timedlock's declaration, fix #1758
  components/posix/include/pthread.h
Labels: in process, License Pass, Sensitive Information Pass
