Repository alibaba/AliOS-Things, pull requests merged in 2022-06, with the labels that each got.

#1782 Replace OSSAccessKeyId with XXXX in ai_agent module
  components/ai_agent/README.md
Labels: License Pass, Sensitive Information Pass

#1784 IssueID:1780:haas python pwm adapter change from hal to aos api.
  components/amp_adapter/platform/aos/peripheral/aos_hal_pwm.c
Labels: in process, License Pass, Sensitive Information Pass

#1786 modify gc7219 datasheet's reference link, fix #1785
  haas_lib_bundles/python/libraries/gc7219/README.md
Labels: in process, License Pass, Sensitive Information Pass

#1803 posix: support timezone and daylight in newlib libc
  components/libc_stub/newlib_stub.c
  components/posix/src/enviro.c
Labels: in process, License Pass, Sensitive Information Pass

#1787 fix PWM duty cycle setting error, fix #1743
  haas_lib_bundles/python/docs/haas_extended_api/driver/pwm.md
Labels: License Pass, Sensitive Information Pass

#1788 modify HaaSPython's brief introduction, fix #1772
  haas_lib_bundles/python/README.md
Labels: in process, License Pass, Sensitive Information Pass

#1802 add source code hyperlink for HaaS EDU K1 version check description
  haas_lib_bundles/python/libraries/haaseduk1/README.md
Labels: in process, License Conflict, Sensitive Information Pass

#1790 IssueID:1701:Workaround for CH395 ethernet chip
  hardware/board/haas100/drivers/ch395_lwip.c
Labels: License Pass, Sensitive Information Pass

#1793 IssueID:1792:Fix documentation on UART API
  haas_lib_bundles/python/docs/haas_extended_api/driver/uart.md
Labels: in process, License Pass, Sensitive Information Pass

#1806 rtl872xd: improve lwip options to fix http test faults
  hardware/chip/rtl872xd/arch/lwipopts.h
Labels: in process, License Pass, Sensitive Information Pass

#1820 add threshold adjustment description for soil monisture sensor, fix #1719
  haas_lib_bundles/python/docs/images/soil_moisture_component_description.png
  haas_lib_bundles/python/libraries/soil_moisture/README.md
Labels: in process, License Conflict, Sensitive Information Pass

#1819 remove duplicate description in network.md, fix #1817
  haas_lib_bundles/python/docs/haas_extended_api/network.md
Labels: in process, License Conflict, Sensitive Information Pass

#1818 IssueID:1794:close bt on nodemcu32s on default.
  components/py_engine/adapter/esp32/fs/boot.py
Labels: in process, License Conflict, Sensitive Information Pass

#1816 IssueID:1815:decrease mp_stack, queue_handler, gui , ota, and linksdk…
  components/osal_aos/freertos/aos_task.c
  components/py_engine/adapter/esp32/main.c
  components/py_engine/adapter/esp32/moduos.c
  components/py_engine/modules/aliyunIoT/module_aiot_mqtt.c
  components/py_engine/modules/display/esp32/moddisplay.c
  components/py_engine/modules/ota/modota.c
Labels: in process, License Pass, Sensitive Information Pass

#1814 fix test register often fail error
  components/linksdk/core/utils/core_http.c
Labels: in process, License Pass, Sensitive Information Pass

#1813 add ulinksdk
  modules/ulinksdk/_uhttp/__init__.py
  modules/ulinksdk/_uhttp/client.py
  modules/ulinksdk/_uhttp/example_client.py
  modules/ulinksdk/_umqtt/__init__.py
  modules/ulinksdk/_umqtt/errno.py
  modules/ulinksdk/_umqtt/robust2.py
  modules/ulinksdk/_umqtt/simple2.py
  modules/ulinksdk/aliyunIoT_test.py
  modules/ulinksdk/crc16.py
  modules/ulinksdk/dynreg.py
  modules/ulinksdk/email/__init__.py
  modules/ulinksdk/email/errors.py
  modules/ulinksdk/email/feedparser.py
  modules/ulinksdk/email/iterators.py
  modules/ulinksdk/email/message.py
  modules/ulinksdk/email/parser.py
  modules/ulinksdk/hashlib/__init__.py
  modules/ulinksdk/hashlib/_sha224.py
  modules/ulinksdk/hashlib/_sha256.py
  modules/ulinksdk/hashlib/_sha384.py
  modules/ulinksdk/hashlib/_sha512.py
  modules/ulinksdk/hmac.py
  modules/ulinksdk/linksdk.py
  modules/ulinksdk/main.py
  modules/ulinksdk/upload_file.py
  modules/ulinksdk/urllib/__init__.py
  modules/ulinksdk/urllib/parse.py
  modules/ulinksdk/warnings.py
Labels: in process, License Pass, Sensitive Information Pass

#1812 Update source code for external and modules
  external/activation/component.mk
  external/cjson/component.mk
  external/external.mk
  external/kv/component.mk
  external/linksdk/component.mk
  external/minizip/include/miniunz.h
  external/minizip/internal/crc32.h
  external/minizip/internal/crypt.h
  external/minizip/internal/deflate.h
  external/minizip/internal/gzguts.h
  external/minizip/internal/inffast.h
  external/minizip/internal/inffixed.h
  external/minizip/internal/inflate.h
  external/minizip/internal/inftrees.h
  external/minizip/internal/ioapi.h
  external/minizip/internal/iowin32.h
  external/minizip/internal/miniunz.h
  external/minizip/internal/trees.h
  external/minizip/internal/unzip.h
  external/minizip/internal/zconf.h
  external/minizip/internal/zconf.in.h
  external/minizip/internal/zlib.h
  external/minizip/internal/zutil.h
  external/minizip/src/adler32.c
  external/minizip/src/compress.c
  external/minizip/src/crc32.c
  external/minizip/src/deflate.c
  external/minizip/src/example.c-bak
  external/minizip/src/gzclose.c
  external/minizip/src/gzio.c-bak
  external/minizip/src/gzlib.c
  external/minizip/src/gzread.c
  external/minizip/src/gzwrite.c
  external/minizip/src/infback.c
  external/minizip/src/inffast.c
  external/minizip/src/inflate.c
  external/minizip/src/inftrees.c
  external/minizip/src/ioapi.c
  external/minizip/src/iowin32.c
  external/minizip/src/minigzip.c-bak
  external/minizip/src/miniunz.c
  external/minizip/src/trees.c
  external/minizip/src/uncompr.c
  external/minizip/src/unzip.c
  external/minizip/src/zutil.c
  external/osal/component.mk
  external/ulog/component.mk
  modules/driver/manifest.py
  modules/modbus/manifest.py
  modules/modules.mk
  mpy-cross/mpy-cross
  ports/stm32/Makefile
  ports/stm32/boards/COLUMBUS/manifest.py
Labels: in process, License Pass, Sensitive Information Pass

#1830 Fix ucloud_ai_demo build fail, fixes #1612
  hardware/chip/haas1000/package.yaml
Labels: in process, License Pass, Sensitive Information Pass

#1837 IssueID:1832:Fix the return value of hal_uart_recv_II
  hardware/chip/haas1000/hal/uart.c
Labels: in process, License Pass, Sensitive Information Pass

#1823 debug: improve mm debug output
  kernel/rhino/k_mm_debug.c
Labels: License Pass, Sensitive Information Pass

#1839 add python:weather_forecast, fixes #1838
  haas_lib_bundles/python/docs/examples/weather_forecast/esp32/README.md
  haas_lib_bundles/python/docs/examples/weather_forecast/esp32/code/board.json
  haas_lib_bundles/python/docs/examples/weather_forecast/esp32/code/gnss.py
  haas_lib_bundles/python/docs/examples/weather_forecast/esp32/code/main.py
  haas_lib_bundles/python/docs/examples/weather_forecast/esp32/code/micropyGNSS.py
  haas_lib_bundles/python/docs/images/weather_forecast/天气预报-步骤简介.png
  haas_lib_bundles/python/docs/images/weather_forecast/天气预报-硬件连线图.png
  haas_lib_bundles/python/docs/images/weather_forecast/天气预报-运行结果.png
Labels: in process, License Pass, Sensitive Information Pass

#1847 rtl872xd: improve log
  hardware/chip/rtl872xd/hal/wifi_port.c
Labels: in process, License Pass, Sensitive Information Pass

#1848 linksdk: improve log
  components/linksdk/portfiles/aiot_port/aos_port.c
Labels: in process, License Pass, Sensitive Information Pass

#1849 haas200: disable haas200 debug log
  hardware/board/haas200/startup/startup.c
Labels: License Pass, Sensitive Information Pass

#1850 haas1000: disable some bsp log
  hardware/chip/haas1000/aos/aos.c
Labels: in process, License Pass, Sensitive Information Pass

#1852 amp_adapter: improve log
  components/amp_adapter/platform/aos/network/aos_network.c
Labels: License Pass, Sensitive Information Pass

#1854 py_engine: add http python module
  modules/http/http.py
Labels: License Pass, Sensitive Information Pass

#1855 oss: add oss python module
  modules/oss/__init__.py
  modules/oss/api.py
  modules/oss/auth.py
  modules/oss/bucket.py
  modules/oss/byhttp/aliot_base64.c
  modules/oss/byhttp/aliot_base64.h
  modules/oss/byhttp/aliot_hmac.c
  modules/oss/byhttp/aliot_hmac.h
  modules/oss/byhttp/aliot_httpapi_oss.c
  modules/oss/byhttp/aliot_httpapi_oss.h
  modules/oss/byhttp/aliot_sha1.c
  modules/oss/byhttp/aliot_sha1.h
  modules/oss/credentials.py
  modules/oss/manifest.py
  modules/oss/modoss.c
  modules/oss/modosshttp.c
  modules/oss/utils.py
  ports/stm32/boards/COLUMBUS/manifest.py
Labels: License Pass, Sensitive Information Pass

#1858 IssueID:1835:Add driver lib for URM37 ultrasonic ranging sensor
  haas_lib_bundles/python/docs/images/ext_urm37_pins.png
  haas_lib_bundles/python/libraries/urm37/README.md
  haas_lib_bundles/python/libraries/urm37/urm37.py
Labels: in process, License Pass, Sensitive Information Pass

#1857 IssueID:1834:Add driver lib for DDS5188 power meter
  haas_lib_bundles/python/docs/images/ext_dds5188_pins.jpg
  haas_lib_bundles/python/libraries/dds5188/README.md
  haas_lib_bundles/python/libraries/dds5188/dds5188.py
Labels: License Pass, Sensitive Information Pass

#1860 IssueID:1859:new watchdog driver framework
  components/drivers/peripheral/watchdog/include/aos/hal/wdg.h
  components/drivers/peripheral/watchdog/include/aos/watchdog.h
  components/drivers/peripheral/watchdog/include/aos/watchdog_core.h
  components/drivers/peripheral/watchdog/include/vfsdev/wdg_dev.h
  components/drivers/peripheral/watchdog/package.yaml
  components/drivers/peripheral/watchdog/src/watchdog.c
  components/drivers/peripheral/watchdog/src/wdg_dev.c
Labels: in process, License Pass, Sensitive Information Pass

#1867 IssueID:1866:设备驱动对VFS的适配层
  components/devfs/README.md
  components/devfs/include/aos/devfs.h
  components/devfs/package.yaml
  components/devfs/src/devfs_aos.c
Labels: in process, License Conflict, Sensitive Information Pass

#1868 IssueID:1863:improve SPI driver framework
  components/drivers/peripheral/spi/example/spi_example.c
  components/drivers/peripheral/spi/include/aos/hal/spi.h
  components/drivers/peripheral/spi/include/aos/spi.h
  components/drivers/peripheral/spi/include/aos/spi_core.h
  components/drivers/peripheral/spi/include/vfsdev/spi_dev.h
  components/drivers/peripheral/spi/package.yaml
  components/drivers/peripheral/spi/src/spi.c
  components/drivers/peripheral/spi/src/spi_dev.c
Labels: in process

#1833 IssueID:1829:add drv8833、paj7620、ds1302 sensor driver.
  haas_lib_bundles/python/docs/images/drv8833.png
  haas_lib_bundles/python/docs/images/ds1302.png
  haas_lib_bundles/python/docs/images/paj7620u2.png
  haas_lib_bundles/python/libraries/drv8833/README.md
  haas_lib_bundles/python/libraries/drv8833/drv8833.py
  haas_lib_bundles/python/libraries/ds1302/README.md
  haas_lib_bundles/python/libraries/ds1302/ds1302.py
  haas_lib_bundles/python/libraries/paj7620/README.md
  haas_lib_bundles/python/libraries/paj7620/paj7620.py
Labels: in process, License Pass, Sensitive Information Pass

#1870 IssueID:1864:improve I2C driver framework
  components/drivers/peripheral/i2c/include/aos/hal/i2c.h
  components/drivers/peripheral/i2c/include/aos/i2c.h
  components/drivers/peripheral/i2c/include/aos/i2c_core.h
  components/drivers/peripheral/i2c/include/vfsdev/i2c_dev.h
  components/drivers/peripheral/i2c/package.yaml
  components/drivers/peripheral/i2c/src/i2c.c
Labels: in process, License Conflict, Sensitive Information Pass

#1873 BugID:1865:Add the source code of fruit scale.
  haas_lib_bundles/python/docs/examples/fruit_scale/m5stack/README.md
  haas_lib_bundles/python/docs/examples/fruit_scale/m5stack/code/board.json
  haas_lib_bundles/python/docs/examples/fruit_scale/m5stack/code/cloudAI.py
  haas_lib_bundles/python/docs/examples/fruit_scale/m5stack/code/ele_scale.py
  haas_lib_bundles/python/docs/examples/fruit_scale/m5stack/code/main.py
  haas_lib_bundles/python/docs/images/fruit_scale/HaaS控制台.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_HaaS控制台查看设备.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_HaaS控制台绑定产品.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_发布产品.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_完成创建产品.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_尚未添加任何功能.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_批量添加.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_新建产品.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_添加设备.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_物联网平台.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_电子秤接线图.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_空产品页.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_设备列表.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_设备证书.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_设备详情.png
  haas_lib_bundles/python/docs/images/fruit_scale/智能水果秤_连线图.jpg
Labels: in process, License Conflict, Sensitive Information Pass

#1879 BugID:1877:Add the source code of electronic barometer.
  haas_lib_bundles/python/docs/examples/ele_barometer/eduk1c/README.md
  haas_lib_bundles/python/docs/examples/ele_barometer/eduk1c/code/airpressure.py
  haas_lib_bundles/python/docs/examples/ele_barometer/eduk1c/code/board.json
  haas_lib_bundles/python/docs/examples/ele_barometer/eduk1c/code/images/airpressure.png
  haas_lib_bundles/python/docs/examples/ele_barometer/eduk1c/code/main.py
  haas_lib_bundles/python/docs/examples/ele_barometer/eduk1c/code/page_airpressure.py
  haas_lib_bundles/python/docs/examples/ele_barometer/eduk1c/code/qmp6988.py
  haas_lib_bundles/python/docs/images/ele_barometer/电子气压计.gif
  haas_lib_bundles/python/docs/images/ele_barometer/电子气压计.jpg
  haas_lib_bundles/python/docs/images/ele_barometer/电子气压计UI元素.png
Labels: in process, License Conflict, Sensitive Information Pass

#1891 boards
  haas_lib_bundles/python/docs/boards/ESP-C3-32S-Kit/README.md
  haas_lib_bundles/python/docs/boards/ESP-S3-12K-Kit/README.md
  haas_lib_bundles/python/docs/boards/ESP32/README.md
  haas_lib_bundles/python/docs/boards/HaaS-EDU-K1/README.md
  haas_lib_bundles/python/docs/boards/HaaS200/README.md
  haas_lib_bundles/python/docs/boards/M5StackCore2/README.md
  haas_lib_bundles/python/docs/boards/STM32-Columbus/README.md
  haas_lib_bundles/python/docs/images/ext_01Studio_Columbus_扩展接口.png
  haas_lib_bundles/python/docs/images/ext_GPS传感器_工作原理1.png
  haas_lib_bundles/python/docs/images/ext_GPS传感器_工作原理2.png
  haas_lib_bundles/python/docs/images/ext_GPS传感器_示意图.png
  haas_lib_bundles/python/docs/images/ext_HaaS_EDU_K1全景图.png
  haas_lib_bundles/python/docs/images/ext_STM32F407_01Studio_pyBoard_Pro_扩展接口.png
  haas_lib_bundles/python/docs/images/ext_columbus_功能配置.png
  haas_lib_bundles/python/docs/images/ext_esp32-c3_功能配置.png
  haas_lib_bundles/python/docs/images/ext_esp32-c3_扩展接口.png
  haas_lib_bundles/python/docs/images/ext_esp32-s3_功能配置.png
  haas_lib_bundles/python/docs/images/ext_esp32-s3_扩展接口.png
  haas_lib_bundles/python/docs/images/ext_esp32_功能配置.png
  haas_lib_bundles/python/docs/images/ext_esp32_扩展接口.png
  haas_lib_bundles/python/docs/images/ext_haas1000芯片框架.png
  haas_lib_bundles/python/docs/images/ext_haas200_功能配置.png
  haas_lib_bundles/python/docs/images/ext_haas200_扩展接口.png
  haas_lib_bundles/python/docs/images/ext_haaseduk1主板功能.png
  haas_lib_bundles/python/docs/images/ext_haaseduk1扩展接口.png
  haas_lib_bundles/python/docs/images/ext_haaseduk1整机接口.png
  haas_lib_bundles/python/docs/images/ext_haas社区.png
  haas_lib_bundles/python/docs/images/ext_m5core2_接口图.png
  haas_lib_bundles/python/docs/images/ext_m5core2_接口扩展.png
Labels: in process, License Conflict, Sensitive Information Pass

#1894 FingerPrintLockExample
  haas_lib_bundles/python/docs/examples/FingerPrintLock/as608.py
  haas_lib_bundles/python/docs/examples/FingerPrintLock/board.json
  haas_lib_bundles/python/docs/examples/FingerPrintLock/main.py
Labels: in process, License Conflict, Sensitive Information Pass

#1895 Remove -Werror option to make sure build pass
  mpy-cross/Makefile
  py/dynruntime.mk
Labels: in process
