Repository alibaba/AliOS-Things, pull requests merged in 2022-04, with the labels that each got.

#1497 Bug fix: declaration is not visible outside of function (#1496)
  components/drivers/core/fbdev/include/fb.h
Labels: License Pass, Sensitive Information Pass

#1501 IssueID:1500:add check for the inet_aton
  components/amp_adapter/platform/aos/network/aos_udp.c
Labels: in process, License Pass, Sensitive Information Pass

#1506 riscv adds rv32 cpu.
  hardware/arch/riscv/include/rv32_32gpr/k_api.h
  hardware/arch/riscv/include/rv32_32gpr/k_arch.h
  hardware/arch/riscv/include/rv32_32gpr/port.h
  hardware/arch/riscv/include/rv32_32gpr/riscv_csr.h
  hardware/arch/riscv/include/rv32fd_32gpr/k_arch.h
  hardware/arch/riscv/include/rv32fd_32gpr/k_types.h
  hardware/arch/riscv/include/rv32fd_32gpr/port.h
  hardware/arch/riscv/include/rv32fd_32gpr/riscv_csr.h
  hardware/arch/riscv/include/rv64fd_32gpr/k_arch.h
  hardware/arch/riscv/include/rv64fd_32gpr/k_types.h
  hardware/arch/riscv/include/rv64fd_32gpr/port.h
  hardware/arch/riscv/include/rv64fd_32gpr/riscv_csr.h
  hardware/arch/riscv/package.yaml
  hardware/arch/riscv/src/rv32_32gpr/dispatcher_c.c
  hardware/arch/riscv/src/rv32_32gpr/dispatcher_s.S
  hardware/arch/riscv/src/rv32_32gpr/irq_dispatcher.c
  hardware/arch/riscv/src/rv32_32gpr/port_c.c
  hardware/arch/riscv/src/rv32_32gpr/port_s.S
Labels: in process

#1504 IssueID:1503:fix wrong sizeof usage
  components/amp_adapter/platform/aos/peripheral/aos_hal_gpio.c
Labels: in process, License Pass, Sensitive Information Pass

#1516 IssueID:1515:add value return for all branches
  components/amp_adapter/platform/aos/peripheral/aos_hal_wdg.c
Labels: in process, License Pass, Sensitive Information Pass

#1509 m5stackcore2 some libs bss moved from internal dram to spiram.
  hardware/board/m5stackcore2/package.yaml
  hardware/board/nodemcu32s/package.yaml
  hardware/chip/espressif_esp32/esp-idf/components/esp32/ld/esp32.extram.bss.ld
  hardware/chip/espressif_esp32/package.yaml
Labels: in process, License Pass, Sensitive Information Pass

#1519 haas1000: fix whitescan bugs in hal/wifi_port.c
  hardware/chip/haas1000/hal/wifi_port.c
Labels: in process, License Pass, Sensitive Information Pass

#1520 mbedtls: fix whitescan bug in library/cipher.c
  components/mbedtls/library/cipher.c
Labels: in process, License Pass, Sensitive Information Pass

#1521 posix: fix whitescan bugs
  components/posix/src/pthread.c
  components/posix/src/temp.c
Labels: in process, License Pass, Sensitive Information Pass

#1523 cli: fix whitescan bugs in cli/iobox
  components/cli/src/iobox/cd.c
  components/cli/src/iobox/cp.c
  components/cli/src/iobox/ls.c
  components/cli/src/iobox/mv.c
Labels: in process, License Pass, Sensitive Information Pass

#1527 IssueID:1526:improve flash driver framework
  components/drivers/peripheral/flash/include/aos/flash.h
  components/drivers/peripheral/flash/include/aos/flash_core.h
  components/drivers/peripheral/flash/include/aos/flashpart.h
  components/drivers/peripheral/flash/include/aos/flashpart_core.h
  components/drivers/peripheral/flash/include/aos/hal/flash.h
  components/drivers/peripheral/flash/package.yaml
  components/drivers/peripheral/flash/src/flash.c
  components/drivers/peripheral/flash/src/flashpart.c
  components/osal_aos/include/aos/kernel.h
  components/osal_aos/package.yaml
  components/osal_aos/rhino/common.c
Labels: in process, License Pass, Sensitive Information Pass

#1528 add ccs811 sensor driver and document
  haas_lib_bundles/python/docs/images/ccs811-front.png
  haas_lib_bundles/python/docs/images/ccs811-sch.png
  haas_lib_bundles/python/libraries/ccs811/README.md
  haas_lib_bundles/python/libraries/ccs811/ccs811.py
Labels: in process, License Pass, Sensitive Information Pass

#1531 provide hx710 sensor for driver and document
  haas_lib_bundles/python/docs/images/hx710-front.png
  haas_lib_bundles/python/libraries/hx710/README.md
  haas_lib_bundles/python/libraries/hx710/hx710.py
Labels: in process, License Pass, Sensitive Information Pass

#1534 provide ttp224 sensor for driver and document
  haas_lib_bundles/python/docs/images/ttp224.png
  haas_lib_bundles/python/libraries/ttp224/README.md
  haas_lib_bundles/python/libraries/ttp224/ttp224.py
Labels: in process, License Pass, Sensitive Information Pass

#1535 provide htb485 module for driver and document
  haas_lib_bundles/python/libraries/htb485/README.md
  haas_lib_bundles/python/libraries/htb485/yuanda_htb485.py
Labels: License Pass, Sensitive Information Pass

#1536 provide zzio606 module for driver and document
  haas_lib_bundles/python/libraries/zzio606/README.md
  haas_lib_bundles/python/libraries/zzio606/zzio606.py
Labels: in process, License Pass, Sensitive Information Pass
